abaltion_1px_random:
  name: pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: true
  load: true
  swap: false
  pixel_mapping: random
abaltion_1px_distance_random:
  name: pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: true
  load: true
  swap: false
  pixel_mapping: distance_random
abaltion_1px_similarity_random:
  name: pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: true
  load: true
  swap: false
  pixel_mapping: similarity_random
abaltion_1px_similarity:
  name: pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: true
  load: true
  swap: false
  pixel_mapping: similarity
abaltion_1px_distance:
  name: pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: true
  load: true
  swap: false
  pixel_mapping: distance
