ablation_iterations_restarts_1:
  name: pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_restarts_2:
  name: pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_restarts_3:
  name: pixle
  restarts: 250
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_restarts_4:
  name: pixle
  restarts: 1000
  max_iterations: 20
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_iterative_1:
  name: pixle
  max_iterations: 50
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_2:
  name: pixle
  max_iterations: 100
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_3:
  name: pixle
  max_iterations: 250
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_4:
  name: pixle
  max_iterations: 500
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_5:
  name: pixle
  max_iterations: 1000
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_6:
  name: pixle
  max_iterations: 2000
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_7:
  name: pixle
  max_iterations: 10000
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: false
  pixel_mapping: random
  update_each_iteration: true