1px_pixle_black:
  name: black_pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 3
  y_dimensions: 3
  save_images: true
  load: false
  swap: false
  pixel_mapping: random
1px_pixle_white:
  name: white_pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 3
  y_dimensions: 3
  save_images: true
  load: false
  swap: false
  pixel_mapping: random
#scratch_3bezier:
#  name: scratch_that
#  pupulation: 50
#  max_patches: 50
#  mutation_rate: 0.8
#  crossover: 0.7
#  scratch_type: bezier
#  save_images: true
#onepixel5:
#  name: onepixel
#  pixels: 5
#  steps: 50
#  popsize: 100