1px_pixle_black:
  name: black_pixle
  restarts: 100
  max_iterations: 20
  x_dimensions: 0.01
  y_dimensions: 0.01
  save_images: true
  load: true
  swap: false
  pixel_mapping: random
#1px_pixle_white_1:
#  name: white_pixle
#  restarts: 100
#  max_iterations: 20
#  pixels_per_iteration: 0.01
#  save_images: true
#  load: true
1px_pixle_white_2:
  name: white_pixle
  restarts: 500
  max_iterations: 50
  pixels_per_iteration: 1
  save_images: true
  load: true
#1px_pixle_white:
#  name: white_pixle
#  restarts: 100
#  max_iterations: 20
#  pixels_per_iteration: 0.01
#  save_images: true
#  load: true
#  swap: false
scratch_3bezier_2:
  name: scratch_that
  pupulation: 50
  max_patches: 50
  mutation_rate: 0.8
  crossover: 0.7
  n_scratches: 2
  scratch_type: bezier
  save_images: true
#scratch_3bezier_v:
#  name: scratch_that
#  pupulation: 50
#  max_patches: 50
#  mutation_rate: 0.8
#  crossover: 0.7
#  scratch_type: bezier
#  save_images: true
#  n_scratches: 3
onepixel5:
  name: onepixel
  pixels: 5
  steps: 50
  popsize: 100
