defaults:
  - model: resnet20
  - dataset: nir_rgb
#  - attack_type: black
  - _self_

paths:
  log: ./runs

params:
  batch_size: 8
  train: 0.85
  val: 0
  test: 0.10
  classes: 9
#  img_size: 224
  images_to_attack_per_label: -1

train_params:
  pre_training_epochs: 100
  lr: 0.001
  log_freq: 10
  device: 0
  pre_trained: false
  adv_training_epochs: 20
  eval_every_n_epochs: 10

params_attack:
  x_dim: 0.1
  y_dim: 0.1
  rest: 1
  max_iter: 1
  attack_per_batch: 20
  pixels_per_iteration: [0.05, 0.4]
  mode: htl
  name: white_pixle


test_params_attack:
  x_dim: 0.1
  y_dim: 0.1
  rest: 100
  max_iter: 50
  attack_per_batch: 0.5
  pixels_per_iteration: 3
  mode: htl
  name: white_pixle
